config/routes.rb
Depot::Application.routes.draw do

  resources :users

  resources :orders

  root to: 'store#index', as: 'store'

  resources :products do
    get :who_bought, on: :member
  end
  resources :carts, only: [:show, :destroy]
  resources :line_items, only: [:create, :destroy]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :line_items, dependent: :destroy

  def add_product(product)
    if line_items.find_by_product_id(product.id)
      line_item = line_items.find_by_product_id(product.id)
      line_item.quantity += 1
      return line_item
    else
      line_item = line_items.build(product_id: product.id)
      line_item.price = product.price
      return line_item
    end
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :product_id

  belongs_to :cart
  belongs_to :product
  belongs_to :order

  validates :product_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  before_create :default_values

  def total_price
    price * quantity
  end

  private

    def default_values
      self.quantity ||= 1
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type

  has_many :line_items

  PAYMENT_TYPES = ["Check", "Credit card", "Purchase order"]

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      self.line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image_url, :title, :price

  has_many :line_items
  has_many :orders, through: :line_items

  validates :title, length: { minimum: 10 }, uniqueness: true
  validates :description, presence: true
  validates :image_url, format: { with: /\w+\.(jpg|gif|png)$/i }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }


  before_destroy :ensure_not_referenced_by_any_line_item

  private
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        true
      else
        errors.add(:base, 'Line Items present')
        false
      end
    end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_secure_password

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

    def current_cart
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = current_cart
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def create
    @cart = current_cart
    @line_item = @cart.add_product(Product.find(params[:product_id]))
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js { @current_item = @line_item }
      end 
    end
  end

  def destroy
    @line_item = current_cart.line_items.find_by_id(params[:id])
    @line_item.destroy
    redirect_to current_cart
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @cart = current_cart #cart display
    @order = Order.new
    if current_cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
    end
  end

  def create
    @order = Order.new(params[:order])
    @order.add_line_items_from_cart(current_cart)
    if @order.save
      OrderNotifier.received(@order).deliver
      redirect_to store_url, notice: "Thank you for your order."
    else
      @cart = current_cart #cart display
      render 'new'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
     @product = Product.find_by_id(params[:id])
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def update
    @product = Product.find_by_id(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find_by_id(params[:id])
    @product.delete
    redirect_to products_path
  end

  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@products = Product.order(:title)
    @cart = current_cart
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes={}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title">Your Cart</div>
<table>
  <%= render cart.line_items %>
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>
<%= button_to 'Checkout', new_order_path, method: :get %>
<%= button_to 'Empty cart', cart, method: :delete, remote: true %>

app/views/carts/destroy.js.erb
$('#cart').hide('fade', 1000);

app/views/carts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<%= render @cart %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Praprog Books Online Store</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body class='<%= controller.controller_name %>' >
		<div id="banner">
			<%= image_tag("logo.png") %>
			<%= @page_title || "Pragmatic Bookshelf" %>
		</div>
		<div id="columns">
			<div id="side">
				<div id="time"><%= Time.now.asctime %></div>
				<% unless request.env['PATH_INFO'].include? "/carts" %>
					<% if @cart %>
						<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
							<%= render @cart %>
						<% end %>
					<% end %>
				<% end %>
				<ul>
					<li><%= link_to 'Home', store_path %></li>
					<li><a href="#faq">Questions</a></li>
					<li><a href="#news">News</a></li>
					<li><a href="#contact">Contact</a></li>
				</ul>
			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/line_items/_line_item.html.erb
<div id='product_<%= line_item.product.id %>'>
  <% if line_item == @current_item %>
    <tr id="current_item">
  <% else %>
    <tr>
  <% end %>
    <td><%= line_item.quantity %>&times;</td>
    <td><%= line_item.product.title %></td>
    <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
    <% if request.env['PATH_INFO'] == cart_path(line_item.cart) %>
      <td><%= button_to "Remove item", line_item, method: :delete %></td>
    <% end %>
  </tr>
</div>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s\n", line_item.quantity, 
                        truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
if($('#notice').is(':visible')) { $('#notice').hide('blind', 1000); }

if ($('#cart').is(':hidden')) { $('#cart').show('fade', 2000); }

$('#cart').html("<%=j render @cart %>");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/order_notifier/received.text.erb
Dear <%= @order.name  %>

Thank you for your recent order from The Pragmatic Store.

You ordered the following items:

<%= render @order.line_items %>

We will send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>
<p>
  This is just to let you know that we've shipped your recent order:
</p>

<table>
  <tr><th colspan="2">Qty</th> <th>Description</th></tr>
  <%= render @order.line_items %>
</table>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <% if @order.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order
        from being saved:
      </h2>

      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :pay_type %><br />
    <%= f.select :pay_type, Order::PAYMENT_TYPES, 
                            prompt: 'Select a payment method' %>
  </div>
  <div class="actions">
    <%= f.submit 'Place Order' %>
  </div>
<% end %>

app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="entry">
  <%= image_tag(product.image_url) %>
  <h3> <%= product.title %> </h3>
  <%= sanitize(product.description) %>
  <div class="price_line">
    <span class="price"> <%= number_to_currency(product.price) %> </span>
    <%= button_to 'Add to Cart', line_items_path(product_id: product), 
                                 id: product.title,
                                 remote: true %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
  
  <table>
  <% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >
  
  <td>
  <%= image_tag(product.image_url, class: 'list_image') %>
  </td>
  
  <td class="list_description" >
  <dl>
  <dt><%= product.title %></dt>
  <dd><%= truncate(strip_tags(product.description),
  length: 80) %></dd>
  </dl>
  </td>
  
  <td class="list_actions" >
  <%= link_to 'Show', product %><br />
  <%= link_to 'Edit', edit_product_path(product) %><br />
  <%= link_to 'Destroy', product,
  confirm: 'Are you sure?',
  method: :delete %>
  </td>
  </tr>
  <% end %>
  </table>
  
  <br />
  
  <%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<% if notice %>
  <p id="notice"> <%= notice %> </p>
<% end %>
<h1>Your Pragmatic Catalog</h1>

<%= render @products %>